import { ArrowRight, Play } from 'lucide-react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';

const aiDesigns = [
    {
        id: 1,
        input_sketch: '/images/services/residential-projects/img(26).webp',
        ai_render: '/images/services/residential-projects/img(18).webp',
        room_type: 'Living Space',
        style: 'Minimalist Modern'
    },
    {
        id: 2,
        input_sketch: '/images/services/residential-projects/img(20).webp',
        ai_render: '/images/services/residential-projects/img(22).webp',
        room_type: 'Master Bedroom',
        style: 'Scandinavian'
    },
    {
        id: 3,
        input_sketch: '/images/services/residential-projects/img(19).webp',
        ai_render: '/images/services/residential-projects/img(17).webp',
        room_type: 'Kitchen Area',
        style: 'Contemporary Indian'
    }
];

export function AIGallery() {
    return (
        <section className="py-24 bg-primary text-white overflow-hidden">
            <div className="container-custom">
                <div className="text-center mb-16">
                    <h4 className="font-space text-xs font-bold uppercase tracking-widest text-secondary mb-4">Aura AI Showcase</h4>
                    <h2 className="text-4xl md:text-5xl xl:text-6xl font-playfair font-bold mb-6">
                        Designs Created with <span className="text-secondary italic">Aura AI</span>
                    </h2>
                    <p className="font-inter text-white/60 max-w-2xl mx-auto text-lg">
                        Real designs generated by Indian homeowners in seconds. Move the slider to see how AI transforms spaces.
                    </p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                    {aiDesigns.map((design, i) => (
                        <motion.div
                            key={design.id}
                            initial={{ opacity: 0, y: 20 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            viewport={{ once: true }}
                            transition={{ delay: i * 0.15 }}
                            className="group relative"
                        >
                            <div className="relative aspect-[4/5] rounded-3xl overflow-hidden mb-6 border border-white/10">
                                {/* Mock slider for visuals */}
                                <img src={design.ai_render} alt="AI Render" className="absolute inset-0 w-full h-full object-cover transition-transform duration-1000 group-hover:scale-105" />

                                {/* Small overlay showing "Before" input */}
                                <div className="absolute top-4 left-4 w-24 aspect-[4/3] rounded-xl overflow-hidden border-2 border-white/20 shadow-2xl z-10">
                                    <img src={design.input_sketch} alt="Input sketch" className="w-full h-full object-cover" />
                                    <div className="absolute inset-x-0 bottom-0 bg-black/60 backdrop-blur-sm text-[8px] font-space text-white uppercase tracking-widest text-center py-1">Input</div>
                                </div>

                                <div className="absolute inset-y-0 left-1/2 w-1 bg-white/30 -translate-x-1/2 cursor-ew-resize hidden md:block">
                                    <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-8 h-8 bg-secondary rounded-full flex items-center justify-center shadow-lg">
                                        <div className="flex gap-1">
                                            <div className="w-0.5 h-3 bg-primary"></div>
                                            <div className="w-0.5 h-3 bg-primary"></div>
                                        </div>
                                    </div>
                                </div>

                                <div className="absolute inset-0 bg-gradient-to-t from-primary/90 via-transparent to-transparent"></div>
                                <div className="absolute bottom-6 left-6 right-6 flex items-end justify-between">
                                    <div>
                                        <h4 className="font-playfair font-bold text-2xl text-white">{design.room_type}</h4>
                                        <p className="font-inter text-secondary text-sm">{design.style}</p>
                                    </div>
                                    <Link to="/aura-ai" className="w-10 h-10 bg-white/10 backdrop-blur-md rounded-full flex items-center justify-center hover:bg-secondary hover:text-primary transition-colors">
                                        <ArrowRight size={18} />
                                    </Link>
                                </div>
                            </div>
                        </motion.div>
                    ))}
                </div>

                <div className="text-center mt-12">
                    <Link to="/aura-ai" className="btn-outline border-secondary text-secondary hover:bg-secondary hover:text-primary inline-flex gap-2">
                        Try Aura AI Free <ArrowRight size={18} />
                    </Link>
                </div>
            </div>
        </section>
    );
}
